### ISSUE TITLE
Disable / enable camera & microphone

### ISSUE THREAD

**Issue by Niels-P** [aiham/opentok-react#14]
Hi, 

I would like to add some callback functions that will block the camera or microphone. Do you have any implementations currently for doing this?

Kind regards,
Niels.

**Comment by aiham** [comment]
@Niels-P Hi, thanks for using opentok-react.

I'm not sure what you mean by `callback functions that will block the camera or microphone`.

I can show you to add a button that toggles camera/microphone on and off for both publishers and subscribers. Is this what you meant?

If you look in the provided example it has such a feature: https://github.com/aiham/opentok-react/tree/master/example

Look in https://github.com/aiham/opentok-react/blob/master/example/components/Publisher.js
and https://github.com/aiham/opentok-react/blob/master/example/components/Subscriber.js

The Publisher uses `publishAudio` and `publishVideo` booleans in the properties passed down to OTPublisher.

The Subscriber uses `subscribeToAudio` and `subscribeToVideo` booleans in the properties passed down to OTSubscriber.

In the example there are checkboxes that toggle these booleans and cause OTPublisher/OTSubscriber to turn audio/video on and off.

Does this help?

**Comment by aiham** [comment]
@Niels-P You can run the example app by following the instructions at https://github.com/aiham/opentok-react#example-app

**Comment by aiham** [comment]
Let me know if you have any other questions. Closing this now.
