### ISSUE TITLE
Publisher breaks when insertDefaultUI = false is used

### ISSUE THREAD

**Issue by pronebird** [aiham/opentok-react#3]
OTK library throws error when `insertDefaultUI: false`:

>You cannot specify a target element if insertDefaultUI is false

So I guess the easy fix would be to check `properties.insertDefaultUI` and provide false instead of `container`

```var publisher = OT.initPublisher(container, this.props.properties);```

**Comment by aiham** [comment]
@pronebird Thanks for reporting this! I've left a comment on your PR.

**Comment by aiham** [comment]
Fixed.
