### ISSUE TITLE
Custom callbacks for publishing and subscribing failures

### ISSUE THREAD

**Issue by Fofir** [aiham/opentok-react#7]
First of all, awesome repo! Thanks!

Is there a way for me to add custom callbacks for errors emitted on the following?

* https://github.com/aiham/opentok-react/blob/master/src/OTPublisher.js#L78
* https://github.com/aiham/opentok-react/blob/master/src/OTSubscriber.js#L27

**Comment by aiham** [comment]
@Fofir Not yet, so proper error handling is on the top of my todo list. I'll do that next then release 0.4.0. I'd like to do that real soon, in the next few days I hope.

**Comment by Fofir** [comment]
@aiham Thanks that's cool!

I had to replace opentok-react with my own implementation to get one of my products running with proper error handling for now, but would certainly go back if it's implemented. Let me know if i can help in any way!

**Comment by aiham** [comment]
@Fofir is your solution generic enough to include in this repo?

**Comment by Fofir** [comment]
Unfortunately not really, it's just something i put up really quick to finish a task for a current sprint which is ending, and am not proud of it just yet.

I can perhaps create a PR win an idea of how it might go here

**Comment by aiham** [comment]
Ah I was just wondering if it was already done. It's up to you if you want to submit a PR, contributions are always welcome.

If not I'll still work on it since it's crucial to properly implementing a robust opentok app.

**Comment by aiham** [comment]
@Fofir What do you think about #10 ?
